### ISSUE TITLE
장소 검색을 위한 services 라이브러리를 추가하며 알게 된 사항

### ISSUE THREAD

**Issue by seojuyn** [whatsmap/whatsmap#39]
![Inked캡처_LI](https://user-images.githubusercontent.com/84673603/141685127-2672e35f-cd80-479a-b90e-edaaf8567146.jpg)

api-config.js 파일을 말하는 걸까요??

**Comment by bang-jeeewon** [comment]
React CRA에 dotenv가 기본으로 포함돼 있어서 별도로 install을 안 해도 된다고 하네용
아래 사이트 참고해서 app key .env에 숨겨놨어요
(https://velog.io/@edie_ko/React-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-API-key-%EC%88%A8%EA%B8%B0%EA%B8%B0.env-%EC%9D%B4%EC%9A%A9)
